name: Hetzner Billing - Slack Alert and Shutdown Tool

on:
  schedule:
    - cron: '*/20 * * * *'  # every 20 minutes
  workflow_dispatch:

jobs:
  monitor-hetzner-billing:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run traffic stats
        env:
          HETZNER_API_TOKEN: ${{ secrets.HETZNER_API_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          THRESHOLD_PERCENT_NOTIF: ${{ vars.THRESHOLD_PERCENT_NOTIF }}
          THRESHOLD_PERCENT_KILL: ${{ vars.THRESHOLD_PERCENT_KILL }}
          SEND_USAGE_NOTIF_ALWAYS: ${{ vars.SEND_USAGE_NOTIF_ALWAYS }}
        run: node scripts/monitor.js
